apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc
    namespace: project
spec:
    ports:
    - name: subscriptions
      targetPort: 3000
      port: {{ .Values.service.port }}
      protocol: TCP
    selector:
       app: subscriptions
    type: {{ .Values.service.type }}