apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: project
  labels:
    app: cart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{.Values.image.tag}}"
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        env:
          - name: SERVICES
            value: cart
      initContainers:
      - name: init-mongodb
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{.Values.image.tag}}"
        command: ['sh', '-c', "until nslookup mongo-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mongo-mongodb; sleep 2; done"]