apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: project
  labels:
    app: demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{.Values.image.tag}}"
        ports:
        - containerPort: 3000
        env:
          - name: SERVICES
            value: api
          - name: PORT
            value: "3000"
        volumeMounts:
          - name: {{ .Release.Name }}-pvclaim
            mountPath: /app/public/assets/data
      volumes:
        - name: {{ .Release.Name }}-pvclaim
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvclaim